apiVersion: v1
kind: Service
metadata:
  name: azure-api-service
  namespace: decode-services
  labels:
    app: azure-api-service
spec:
  selector:
    app: azure-api
  ports:
    - port: 80
      targetPort: 8084
  type: ClusterIP
