apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api-deployment
  namespace: decode-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
        - name: db-api-container
          image: decodekubernetesacr.azurecr.io/collab-azure/decode-dbapi:latest
          resources:
            requests:
              cpu: 50m
              memory: 450Mi
            limits:
              cpu: 200m
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

---        

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-jdb-api-deployment
  namespace: decode-services
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: db-api-deployment
  targetCPUUtilizationPercentage: 80 # target CPU utilization