apiVersion: v1
kind: Service
metadata:
  name: db-api-service
  namespace: decode-services
  labels:
    app: db-api-service
spec:
  selector:
    app: db-api
  ports:
    - port: 80
      targetPort: 8083
  type: ClusterIP
