apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: decode-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana-container
          image: decodekubernetesacr.azurecr.io/collab-azure/decode-grafana:latest
          resources:
            requests:
              cpu: 20m
              memory: 56Mi
            limits:
              cpu: 25m
              memory: 64Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          
---        

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-grafana-deployment
  namespace: decode-services
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: grafana-deployment
  targetCPUUtilizationPercentage: 80 # target CPU utilization
