apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-api-deployment
  namespace: decode-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-api
  template:
    metadata:
      labels:
        app: mqtt-api
    spec:
      containers:
        - name: mqtt-api-container
          image: decodekubernetesacr.azurecr.io/collab-azure/decode-mqtt:latest
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 288Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8087

---        

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-mqtt-api-deployment
  namespace: decode-services
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: mqtt-api-deployment
  targetCPUUtilizationPercentage: 80 # target CPU utilization