apiVersion: v1
kind: Service
metadata:
  name: mqtt-api-service
  namespace: decode-services
  labels:
    app: mqtt-api-service
spec:
  selector:
    app: mqtt-api
  ports:
    - port: 80
      targetPort: 8087
  type: ClusterIP
