apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: decode-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui-container
        image: decodekubernetesacr.azurecr.io/collab-azure/decode-ui:latest
        resources:
          requests:
            cpu: 20m
            memory: 200Mi
          limits:
            cpu: 120m
            memory: 256Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
---        

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ui-deployment
  namespace: decode-services
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: ui-deployment
  targetCPUUtilizationPercentage: 80 # target CPU utilization
