apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: decode-services
  labels:
    app: ui-service
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP