apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-metrics-deployment
  namespace: decode-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-metrics
  template:
    metadata:
      labels:
        app: container-metrics
    spec:
      containers:
        - name: container-metrics-container
          image: decodekubernetesacr.azurecr.io/collab-azure/decode-container-metrics:latest
          resources:
            requests:
              cpu: 20m
              memory: 56Mi
            limits:
              cpu: 150m
              memory: 100Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
