apiVersion: v1
kind: Service
metadata:
  name: device-metrics-service
  namespace: decode-metrics
  labels:
    app: device-metrics-service
spec:
  selector:
    app: device-metrics
  ports:
    - port: 80
      targetPort: 9092
  type: ClusterIP