apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: decode-metrics
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9090'
  labels:
    app: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - port: 80
      targetPort: 9090
  type: ClusterIP