apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-managed-ssd-data
  namespace: decode-metrics
  labels:
    app: prometheus-pvc-deployment
spec:
  storageClassName: managed-standard-ssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi